version: '3.8'

services:
  todo-app:
    image: a0s21en5/todo-app:latest
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: todo-app
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.example.description=Angular Todo App"
      - "com.example.version=1.0.0"